global:
  scrape_interval: 5s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alert_rules.yml

scrape_configs:
  - job_name: "rag_api"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]
